name: Deploy Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

env:
  ZIG_VERSION: 0.17.0-dev.1282+c0f9b51d8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Cache Zig
        id: cache-zig
        uses: actions/cache@v4
        with:
          path: ~/zig
          key: zig-${{ env.ZIG_VERSION }}

      - name: Install Zig
        if: steps.cache-zig.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/zig
          curl -L \
            "https://ziglang.org/download/${ZIG_VERSION}/zig-x86_64-linux-${ZIG_VERSION}.tar.xz" \
            | tar -xJ --strip-components=1 -C "$HOME/zig"

      - name: To path
        run: |
          echo "$HOME/zig" >> "$GITHUB_PATH"

      - name: Generate HTML
        run: zig build parse

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./zig-out/generated
  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
